# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy to GitHub Pages

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Format code with Prettier
              run: npm run prettier

            - name: Confirm Prettier code formatting
              run: npm run prettier-check

            - name: Build
              run: npm run build

            - name: Test
              run: npm test

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run release

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build

            - name: Build Storybook
              run: npm run build-storybook

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: './storybook-static'
                  production-branch: main
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: 'Deploy from GitHub Actions'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
